---
title: "기말고사"
author: "이상우"
date: "`r Sys.Date()`"
output: 
  html_document:
    hightlight : textnate
    theme: cosmo
    toc: yes
    toc_cepth: 2
    toc_float: yes
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = F)
library(data.table)
library(jstable)
#install.packages("data.table")
#install.packages("jstable")
```

## Table 1 만들기

```{r cars}
a <- fread("https://raw.githubusercontent.com/jinseob2kim/lecture-snuhlab/master/data/example_g1e.csv")
vars.factor <-grep("Q_", names(a), value = T)

for (v in vars.factor){
  a[[v]] <- factor(a[[v]])
}


vars.tb1 <- names(a)[-c(1:3)]

tb1 <- CreateTableOneJS(vars = vars.tb1, strata = "EXMD_BZ_YYYY", data = a)
#knitr::kable(tb1$table, caption = tb1$caption)

#install.packages("DT")
DT::datatable(tb1$table, caption = tb1$caption)

```
head(a)

## 회귀분석

### 선형회귀분석

```{r}
library(survival)
res.reg <- glm(time ~ rx + age + sex, data = colon)
tb.reg <- glmshow.display(res.reg)
knitr::kable(tb.reg$table, caption = tb.reg$first.line)
```

### 로지스틱

```{r}
library(survival)
res.logistic <- glm(status ~ rx + age + sex, data = colon, family = binomial)
tb.logistic <- glmshow.display(res.logistic)
knitr::kable(tb.logistic$table, caption = tb.logistic$first.line)
```

### 생존분석

#### Cox

```{r}
library(survival)
res.cox <- coxph(Surv(time, status) ~ rx + age + sex, data = colon, model = T)
tb.cox <- cox2.display(res.cox)
knitr::kable(tb.cox$table, caption = tb.cox$caption)
```

#### kaplan-meier

```{r}
#install.packages("jskm")

res.km <- survfit(Surv(time, status) ~ rx, data = colon)

jskm::jskm(res.km, table = T, pval = T, label.nrisk = "No. at risk", size.label.nrisk = 8, 
     xlabs = "Time(Day)", ylabs = "Survival", ystratalabs = c("Obs", "Lev", "Lev + 5FU"), ystrataname = "rx",
     marks = F, timeby = 365, xlims = c(0, 3000), ylims = c(0.25, 1), showpercent = T)

```
